spring:
  ai:
    ollama:
      base-url: http://192.168.31.212:11434
      chat:
        options:
          internal-tool-execution-enabled: true
    # 注意：观测数据可能存在敏感信息！
    chat:
      client:
        observations:
          # 记录调用输入
          include-input: true
      observations:
        # 记录 LLMs 输出
        include-completion: true
        # 记录 prompt
        include-prompt: true
        include-error-logging: true


things:
  ai:
    models:
      - model: deepseek-r1:1.5b
        supplier: ollama
        desc: "deepseek-r1 的 1.5b 模型，不支持tools"
      - model: deepseek-r1:latest
        supplier: ollama
        desc: "deepseek-r1 的 7b 模型，不支持tools"
      - model: qwen3:1.7b
        supplier: ollama
        desc: "qwen3 的 1.7b 模型"
      - model: deepseek-r1
        supplier: dashScope
        desc: "包含 671B 参数，激活 37B，在后训练阶段大规模使用了强化学习技术，在仅有极少标注数据的情况下，极大提升了模型推理能力，尤其在数学、代码、自然语言推理等任务上"
      - model: deepseek-v3
        supplier: dashScope
        desc: "MoE 模型，671B 参数，激活 37B，在 14.8T Token 上进行了预训练，在长文本、代码、数学、百科、中文能力上表现优秀"
      - model: qwen-plus
        supplier: dashScope
        desc: "效果、速度、成本均衡"
      - model: qwen-turbo
        supplier: dashScope
        desc: "适合简单任务，速度快、成本极低"
      - model: qwen-max
        supplier: dashScope
        desc: "适合复杂任务，推理能力最强"
      - model: qwen-long
        supplier: dashScope
        desc: "适合大规模文本分析，效果与速度均衡、成本较低"


logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    org.springframework.ai.ollama.api: INFO
    org.springframework.http.codec: INFO
    reactor: INFO
